'use client';

export default function TheLastHumanCurator() {
  return (
    <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '0 2rem', paddingTop: '4rem', paddingBottom: '4rem' }}>
      <div style={{
        fontSize: '1.056rem',
        color: '#ffffff',
        lineHeight: '1.5',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
        marginBottom: '0.5rem'
      }}>
        Unrealized Curatorial Scenario (2026)
      </div>

      <h1 style={{
        fontFamily: 'system-ui',
        fontSize: '3.63rem',
        fontWeight: '400',
        color: '#ffffff',
        marginBottom: '1rem',
        lineHeight: '1.3'
      }}>
        The Last Human Curator
      </h1>

      <h2 style={{
        fontSize: '1.815rem',
        fontWeight: '300',
        color: '#ffffff',
        marginBottom: '2rem',
        lineHeight: '1.4'
      }}>
        Institutional Futures
      </h2>

      <div style={{
        position: 'relative',
        aspectRatio: '16/9',
        borderRadius: '0.8rem',
        overflow: 'hidden',
        marginBottom: '3rem'
      }}>
        <img
          src="/assets/nav_images/tlhc.jpg"
          alt="The Last Human Curator"
          style={{
            width: '100%',
            height: '100%',
            objectFit: 'cover'
          }}
        />
      </div>

      <p style={{
        fontSize: '1.5rem',
        fontWeight: '500',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '2rem',
        marginTop: '5rem'
      }}>
        The Last Human Curator imagines a near-future museum in which artificial intelligence systems have assumed nearly all curatorial and institutional functions: acquisitions, exhibition design, interpretation, audience analysis, conservation, and historical contextualization.
      </p>

      <h3 style={{
        fontSize: '2.178rem',
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: '1.5rem',
        marginTop: '3rem'
      }}>
        Concept
      </h3>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '1.5rem'
      }}>
        The institution operates with flawless efficiency.
      </p>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '1.5rem'
      }}>
        Exhibitions are generated through predictive systems trained on cultural datasets, behavioral analytics, and algorithmic optimization models.
      </p>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '1.5rem'
      }}>
        And yet one human curator remains.
      </p>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '1.5rem'
      }}>
        Their role is no longer to organize exhibitions or select artworks. Instead, they function as a final point of interruption within an otherwise autonomous cultural system.
      </p>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '1.5rem'
      }}>
        Occasionally, the curator rejects proposals generated by the institution’s AI systems — not through measurable reasoning, but through hesitation, ambiguity, intuition, contradiction, or private human experience that cannot be fully translated into machine logic.
      </p>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '3rem'
      }}>
        The project examines what remains uniquely human within cultural production once interpretation, classification, and curation become computational processes.
      </p>

      <h3 style={{
        fontSize: '2.178rem',
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: '1.5rem',
        marginTop: '3rem'
      }}>
        Exhibition Structure
      </h3>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '1.5rem'
      }}>
        The exhibition unfolds as a sequence of interconnected spatial environments:
      </p>

      <div style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '3rem'
      }}>
        • Orientation Hall — The Efficient Museum
        <br />
        Real-time visitor analytics, predictive recommendation systems, and AI-generated institutional interfaces.
        <br />
        <br />
        • Machine Curated Galleries
        <br />
        Exhibition rooms organized entirely through algorithmic curatorial logic.
        <br />
        <br />
        • Invisible Infrastructure Room
        <br />
        Server systems, datasets, recommendation engines, and computational architectures made visible.
        <br />
        <br />
        • Archive of Rejected Exhibitions
        <br />
        Unrealized AI-generated exhibitions, canceled proposals, incomplete institutional fragments.
        <br />
        <br />
        • Office of the Last Human Curator
        <br />
        A quiet room containing handwritten notes, unfinished thoughts, marked-up printouts, and personal traces.
        <br />
        <br />
        • Silence Chamber
        <br />
        An almost empty architectural space where the system has intentionally stopped producing output.
      </div>

      <h3 style={{
        fontSize: '2.178rem',
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: '1.5rem',
        marginTop: '3rem'
      }}>
        Participants
      </h3>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '1.5rem'
      }}>
        The exhibition combines works and contributions from:
      </p>

      <div style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '1.5rem'
      }}>
        • contemporary artists
        <br />
        • AI researchers
        <br />
        • sound artists
        <br />
        • speculative designers
        <br />
        • architects
        <br />
        • writers
        <br />
        • machine-learning systems
        <br />
        • generative language models
        <br />
        • institutional archives
      </div>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '3rem'
      }}>
        The AI systems themselves function as active curatorial participants within the exhibition structure.
      </p>

      <h3 style={{
        fontSize: '2.178rem',
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: '1.5rem',
        marginTop: '3rem'
      }}>
        Media
      </h3>

      <div style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '1.5rem'
      }}>
        • Generative AI systems
        <br />
        • Algorithmic recommendation engines
        <br />
        • Installation
        <br />
        • Sound environments
        <br />
        • Dynamic text generation
        <br />
        • Speculative institutional interfaces
        <br />
        • Architectural intervention
        <br />
        • Procedural cinema
        <br />
        • Archival materials
        <br />
        • Data visualization
        <br />
        • Light environments
      </div>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '3rem'
      }}>
        No humanoid robotics are used. The intelligence of the exhibition remains infrastructural rather than embodied.
      </p>

      <h3 style={{
        fontSize: '2.178rem',
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: '1.5rem',
        marginTop: '3rem'
      }}>
        Duration
      </h3>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '1.5rem'
      }}>
        Suggested exhibition duration: 8–12 weeks
      </p>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '1.5rem'
      }}>
        The exhibition continuously evolves through:
      </p>

      <div style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '1.5rem'
      }}>
        • live data processing,
        <br />
        • changing recommendation structures,
        <br />
        • adaptive exhibition sequencing,
        <br />
        • generative textual outputs,
        <br />
        • variable visitor interaction patterns.
      </div>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '3rem'
      }}>
        No two visits are fully identical.
      </p>

      <h3 style={{
        fontSize: '2.178rem',
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: '1.5rem',
        marginTop: '3rem'
      }}>
        Spatial Requirements
      </h3>

      <div style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '3rem'
      }}>
        • Approx. 800–1,500 m²
        <br />
        • Modular gallery architecture
        <br />
        • Controlled lighting conditions
        <br />
        • Server / technical infrastructure space
        <br />
        • Multi-channel audio capability
        <br />
        • Networked computational systems
        <br />
        • Quiet architectural zones for low-stimulation environments
      </div>

      <h3 style={{
        fontSize: '2.178rem',
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: '1.5rem',
        marginTop: '3rem'
      }}>
        Curatorial Keywords
      </h3>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '3rem'
      }}>
        Artificial Intelligence · Institutional Critique · Automation · Computational Culture · Speculative Museums · Post-Human Curation · Algorithmic Governance · Silence · Friction · Latency · Human Ambiguity
      </p>

      <h3 style={{
        fontSize: '2.178rem',
        fontWeight: '600',
        color: '#ffffff',
        marginBottom: '1.5rem',
        marginTop: '3rem'
      }}>
        Core Question
      </h3>

      <p style={{
        fontSize: '1.331rem',
        color: '#ffffff',
        lineHeight: '1.7',
        marginBottom: '3rem'
      }}>
        If artificial intelligence can already classify, generate, interpret, preserve, and curate culture — what remains uniquely human within the museum?
      </p>

      <div style={{
        display: 'flex',
        flexWrap: 'wrap',
        gap: '0.5rem',
        marginBottom: '3rem'
      }}>
        <span style={{
          fontSize: '1.056rem',
          color: '#4fd3ff',
          backgroundColor: 'rgba(7, 117, 153, 0.1)',
          padding: '0.25rem 0.75rem',
          borderRadius: '0.25rem',
          textTransform: 'uppercase',
          letterSpacing: '0.05em'
        }}>
          AI Curation
        </span>
        <span style={{
          fontSize: '1.056rem',
          color: '#4fd3ff',
          backgroundColor: 'rgba(7, 117, 153, 0.1)',
          padding: '0.25rem 0.75rem',
          borderRadius: '0.25rem',
          textTransform: 'uppercase',
          letterSpacing: '0.05em'
        }}>
          Museum Futures
        </span>
        <span style={{
          fontSize: '1.056rem',
          color: '#4fd3ff',
          backgroundColor: 'rgba(7, 117, 153, 0.1)',
          padding: '0.25rem 0.75rem',
          borderRadius: '0.25rem',
          textTransform: 'uppercase',
          letterSpacing: '0.05em'
        }}>
          Human Judgment
        </span>
      </div>

      <div style={{
        borderTop: '1px solid #2a2a2a',
        paddingTop: '2rem'
      }}>
        <a
          href="/ideas"
          style={{
            fontSize: '1rem',
            color: '#077599',
            textDecoration: 'none',
            transition: 'color 0.2s ease'
          }}
          onMouseEnter={(e) => {
            e.currentTarget.style.color = '#ffffff';
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.color = '#077599';
          }}
        >
          ← Back to Ideas
        </a>
      </div>
    </div>
  );
}
